### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by LucasLueSL** [XiaoYuOvO/MITE1.18.2Pub#2]
1. 铜矿石铜锭铜块可以保持1.18原版的色调，所有铜制物品都可以使用与1.18原版相同的色调
2. 所有铁砧的放置音效都是石头的，望与原版同步，而且没有改变钨砧的纹理
3. 部分矿物块（包括绿宝石，金，钻石，铁，铜，下界合金）的放置音效变成了石头的，而MITE新增的矿物块都变成石头音效（包括放置摧毁行走）了，望改进
4. 石熔炉的纹理未修改
5. MITE桶的纹理未修改
6. 进度标签"结构!"最好去掉感叹号，改为"结构"，而且沙漠神殿，丛林神殿和末地城的描述没有中文
7. MITE矿石的译名应该从“〇〇矿”改成“〇〇矿石”，与原版译名同步
8. MITE矿石纹理风格未与1.17+的风格保持一致
9. 进度“结构!”标签中的“丛林神殿”的描述应当改为“丛林神庙”

**Comment by beifeng233** [comment]
还有结构里的废弃传送门的要求是进入地狱，应该改为进入下界
